version: '3.8'
services:
   dev-db:
    image: postgres:15
    container_name: nest-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: